version: '3.7'
services:
  app:
    container_name: digitalvisibilityindex-app
    build: .
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
  composer:
    image: composer:latest
    volumes:
      - ./app:/app
    command: "composer install --ignore-platform-reqs"
